@extends('layout.base_page')

@section('content')
<main id="main">
    <section class="breadcrumbs">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <ol>
                    <li><a href="{{ route('page.home') }}">Home</a></li>
                    <li>Sobre</li>
                </ol>
            </div>
        </div>
    </section>

    <section class="inner-page">
        <div class="container" data-aos="fade-up" data-aos-delay="100">
            <div class="row">
                <div class="col-12" id="description">
                    <p class="MsoNormal"><strong>NOSSA HISTÓRIA</strong></p>
                    <p class="MsoNormal"><strong>O CHAMADO DE DEUS</strong></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">No final de 2011, o Reverendo Aguiar Valvassoura, da Igreja do Nazareno - Central de Campinas, expos seu desejo de abrir uma Igreja do Nazareno no estado do <strong>Amapá</strong>, sendo este o único estado do Brasil que ainda não tinha uma Igreja do Nazareno. Logo, em Abril de 2013, a Igreja do Nazareno – Central de Campinas, enviou a Família Sant’Ana (Pr. Gustavo e Pra. Luciana), em uma viagem missionária, para iniciar um trabalho evangelístico em Macapá.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">A Família Sant’Ana partiu em direção ao Amapá, e de carro cortaram 7 estados, até chegarem em Macapá. Ao chegarem na Capital, iniciaram o trabalho evangelístico com pequenos grupos, que se reuniam em casas e faziam evangelizações. Passado 1 ano iniciou-se um novo desafio...</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">E em Julho de 2014, um grupo de 90 Jovens do Nazateen – Central de Campinas, vieram à Macapá para a construção do 1º Templo da Igreja, que ficava na Rua Manuel Eudóxio Pereira, entre Av. Fab e Av. Procópio Rola. Foi assim que surgiu a Igreja do Nazareno em Macapá!</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">Ali foi onde iniciou um grande trabalho de dedicação e amor... E lá tivemos nosso primeiro culto e primeiros batismos. Assim sendo, já não éramos grupos pequenos, e sim, uma família!</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">A família foi crescendo ainda mais, e com o crescimento da igreja foi necessário aumentar o templo e mudar para um lugar maior, e pela graça de Deus, hoje estamos em um novo endereço, localizado na Rua Hildemar Maia, bairro Santa Rita.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><strong><em>Deus fez muitas maravilhas, mas ainda tem grandes coisas para acontecer nesse lugar ...</em></strong></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><strong><em>&nbsp;</em></strong></p>
                    <p class="MsoNormal" style="text-align:justify"><strong>QUEM SOMOS</strong></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><strong>A IGREJA DO NAZARENO É UMA IGREJA CRISTÃ.</strong> As primeiras palavras do nosso manual declaram que a Igreja do Nazareno, desde seu início, confessa ser um ramo da “única Igreja Santa, Universal, e Apostólica”. Aceitamos e endossamos os credos, redigidos nos primeiros séculos da história da Igreja Cristã, como expressões da nossa fé e identidade. Ou seja, a Igreja do Nazareno abraça como sua, a história daqueles redimidos pela graça, por meio do Senhor Jesus Cristo, através dos séculos.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><strong>A IGREJA DO NAZARENO É UMA IGREJA PROTESTANTE.</strong> Isto significa que seu caráter é nitidamente forjado pela Reforma Protestante, do século XVI. Neste amplo movimento de restauração da Igreja Cristã, reafirmou-se que a Bíblia é a autoridade final da definição de nossos postulados. A salvação é uma dádiva da graça de Deus, não uma conquista humana, por meio de boas obras. Os nazarenos se encontram entre aqueles que acreditam que Deus oferece sua graça a todas as pessoas. Todos podem ser alcançados pela redenção. Todos os crentes têm privilégio e a responsabilidade de atuar como “sacerdotes” (Sacerdócio Universal),relacionando-se com Deus pela mediação do Senhor Jesus Cristo.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><strong>A IGREJA DO NAZARENO É MARCADA, EM SUA IDENTIDADE, PELA HERANÇA WESLEYANA.</strong> Entre as contribuições distintivas do Avivamento Wesleyano, está a ênfase na experiencia pessoal com o Espírito Santo; na importância da santificação dos crentes, ou seja, no crescimento espiritual, gradual rumo à semelhança de Cristo.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><strong>A IGREJA DO NAZARENO É UMA IGREJA DE “SANTIDADE”.</strong> Nossa Igreja cresceu em meio a focos de avivamento, nos Estados Unidos, na segunda metade do Século XIX. O anseio por uma vida incorrupta aqueceu o coração de inúmeros crentes. Retiros especiais em áreas rurais, e trabalho missionário arrojado, foram evidências de extraordinário despertamento.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">O fundamento da Igreja do Nazareno foi edificado pela união de várias igrejas de santidade. Essas junções ocorreram, periodicamente desde 1890. Em 1908, ano chave no processo de união, alguns adicionamentos vitais aceleraram o processo, que culminou na fundação oficial da Igreja.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">A Igreja tem se expandindo mundialmente, devido a programas missionários vigorosos. Isto a projetou, como uma igreja de visão global, que ministra em mais de 150 (cento ecinquenta) diferentes países. A Igreja do Nazareno, como outras denominações, tem seu próprio “ramo” na grande “árvore genealógica!” da Igreja Cristã. Como nazarenos, não deixamos de proclamar, que no centro do unificante, no tronco, está o Senhor Jesus Cristo, O Senhor da Igreja Universal, dos primogênitos arrolados nos céus.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><br></p>
                    <p class="MsoNormal" style="text-align:justify"><strong>NOSSOS VALORES ESSENCIAIS</strong></p>
                    <p class="MsoListParagraphCxSpFirst" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify;text-indent:-18.0pt;mso-list:l0 level1 lfo1"><em>1.<span style="font-style: normal; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;</span></em><em>Somos um Povo Cristão</em></p>
                    <p class="MsoListParagraphCxSpMiddle" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify">Como membros da Igreja de Deus vivo, espalhada ao redor do mundo através da história, nos unimos aos verdadeiros cristãos na proclamação do senhorio absoluto de Jesus Cristo.</p>
                    <p class="MsoListParagraphCxSpMiddle" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify;text-indent:-18.0pt;mso-list:l0 level1 lfo1"><em>2.<span style="font-style: normal; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;</span></em><em>Somos um Povo de Santidade</em></p>
                    <p class="MsoListParagraphCxSpMiddle" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify">Somos chamados à santidade pelo Deus Santo. Cremos que batizados no Espírito Santo, podemos seguir a carreira que nos está proposta, e andar à semelhança de Cristo Jesus, nosso SENHOR.</p>
                    <p class="MsoListParagraphCxSpMiddle" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify;text-indent:-18.0pt;mso-list:l0 level1 lfo1"><em>3.<span style="font-style: normal; font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: &quot;Times New Roman&quot;;">&nbsp;&nbsp;&nbsp;&nbsp;</span></em><em>Somos um Povo com uma Missão</em></p>
                    <p class="MsoListParagraphCxSpLast" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify">Fomos enviados ao mundo e respondemos ao chamado de Cristo. Somos capacitados pelo Espírito Santo, para proclamar o Evangelho da Graça ecooperar ativamente na edificação da Igreja e na expansão do Reino Eterno do Senhor.</p>
                    <p class="MsoListParagraphCxSpLast" style="margin-left:21.3pt;mso-add-space:auto;text-align:justify"><br></p>
                    <p class="MsoNormal"><strong>NOSSA MISSÃO</strong><span style="font-family:&quot;inherit&quot;,serif;mso-bidi-font-family:Arial;color:black;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm"></span></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">A missão da Igreja do Nazareno é responder à Grande Comissão de Cristo ir e fazer discípulos de todas as nações</p>
                    <p class="MsoNormal" style="text-align:justify"><strong><em><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%">“Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai, do Filho e do Espírito Santo” (Mateus 28:19)</span></em></strong></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">A Igreja do Nazareno existe com o fim de servir como instrumento para o avanço do Reino de Deus, através da pregação e ensino do Evangelho por todo o mundo. A nossa bem definida comissão é a de preservar e propagar a santidade cristã tal como explícitanas Escrituras, através da conversão de pecadores, da redenção de apostatados e da inteira santificação dos crentes.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt"><br></p>
                    <p class="MsoNormal"><strong>NOSSO OBJETIVO</strong></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">O objetivo primário da Igreja do Nazareno é avançar o Reino de Deus através da preservação e propagação da santidade cristã, como explícitas nas Escrituras.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">Os objetivos críticos da Igreja do Nazareno são a santa comunhão cristã, a conversão de pecadores, a inteira santificação dos crentes, a sua edificação em santidade e a simplicidade e o poder espiritual manifestos na primitiva Igreja do Novo Testamento, juntamente com a pregação do Evangelho a toda a Criatura.</p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">Nosso objetivo é de ordem espiritual, a saber, evangelizar como resposta à Grande Comissão do nosso Senhor: </p>
                    <p class="MsoNormal" style="text-align:justify"><strong><em><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%">“Ide, fazei discípulos de todas as nações”</span></em></strong><strong><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%"> (Mateus 28:19)</span></strong></p>
                    <p class="MsoNormal" style="margin-bottom:0cm;text-align:justify"><strong><em><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%">“E Jesus lhes disse outra vez:</span></em></strong></p>
                    <p class="MsoNormal" style="text-align:justify"><strong><em><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%">– Que a paz esteja com vocês! Assim como o Pai me enviou, eu também envio vocês.”</span></em></strong><strong><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%"> (João 20:21)</span></strong></p>
                    <p class="MsoNormal" style="margin-bottom:0cm;text-align:justify"><strong><em><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%">“E disse-lhes:</span></em></strong></p>
                    <p class="MsoNormal" style="text-align:justify"><strong><em><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%">– Vão por todo o mundo e preguem o evangelho a toda criatura.”</span></em></strong><strong><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%"> (Marcos 16:15) </span></strong></p>
                    <p class="MsoNormal" style="text-align:justify;text-indent:14.2pt">Cremos que este alvo pode ser alcançado através de um governo e práticas, incluindo posições doutrinárias respeitantes à fé e padrões de moralidade e de estilo devida testados pelo tempo.<strong><span style="font-size:11.0pt;mso-bidi-font-size:10.0pt;line-height:107%"></span></strong></p>
                    <p class="MsoNormal">&nbsp;</p>
                    <p class="MsoNormal"><strong>NO QUE CREMOS</strong></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Cremos em um só Deus - o Pai, o Filho e o Espírito Santo.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span class="wixguard"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">​</span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Cremos que as Escrituras do Antigo e do Novo Testamento, dadas por inspiração plenária, contêm toda averdade necessária à fé e ao viver cristão.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span class="wixguard"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">​</span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Cremos que o homem nasce com uma natureza caída e, portanto, está inclinado ao mal, e isso continuamente.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span class="wixguard"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">​</span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Acreditamos que os impenitentes finalmente estão irremediavelmente e eternamente perdidos.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span class="wixguard"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">​</span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Cremos que o sacrifício de Jesus Cristo é para toda a raça humana; E que todo aquele que se arrepender e crer no Senhor Jesus Cristo é justificado e regenerado e salvo do domínio do pecado.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span class="wixguard"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">​</span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Acreditamos que os crentes devem ser santificados inteiramente, após a regeneração, por meio da fé no Senhor Jesus Cristo.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span class="wixguard"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">​</span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Acreditamos que o Espírito Santo testemunha o novo nascimento, e também a inteira santificação dos crentes.</span></p>
                    <p style="text-align: justify;"></p>
                    <p class="font9" style="margin:0cm;text-align:justify;vertical-align:baseline"><span style="font-family:&quot;Arial&quot;,sans-serif;color:#2F2E2E;border:none windowtext 1.0pt;mso-border-alt:none windowtext 0cm;padding:0cm">Cremos que nosso Senhor voltará, os mortos ressuscitarão e o julgamento final acontecerá.</span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black"></span></p>
                </div>
            </div>
        </div>
    </section>
  </main>
@endsection